### PR TITLE
Get started section in the readme

### PR DESCRIPTION
**Pull request by m-kuhn**
Referencees #8

### CODE REVIEW

**Comment by chfritz** [comment]
These instruction are for the deployed app, not the source code, but I agree that it is probably useful to have them here, so thanks!

**Comment by m-kuhn** [comment]
I wrote the patch before I noticed the issue.

Just wondering, is the same network even a requirement?

**Comment by chfritz** [comment]
Only for file management. Everything else works even when you are on separate networks.

**Comment by m-kuhn** [comment]
So that should probably be rewritten to be more precise.

Unfortunately, the file management didn't even work for me on the same network... Should I open a new issue for this - and what information would be required?

**Comment by chfritz** [comment]
Yes, I think it's broken right now for me, too. Feel free to take a crack at it. I probably won't get around to it in a while.

**Pull request merged**
